version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - chmod +x check-rds-snapshots.sh
      - chmod +x delete-old-snapshots.sh
      - cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}
      - export KEYCLOAK_USER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id keycloak --query SecretString --output text | jq -r .KEYCLOAK_USER_PASSWORD)
      - cd eks-kubeflow
      - terraform init -reconfigure
  build:
    commands:   
      - |
        set +e # Disable exit on error
        terraform apply -input=false tfplan
        APPLY_EXIT_CODE=$?
        if [ $APPLY_EXIT_CODE -ne 0 ]; then
          echo "Terraform apply failed. Running destroy to clean up resources..."
          terraform state rm module.eks.kubernetes_config_map_v1_data.aws_auth || true
          terraform destroy -auto-approve -var "environment=dev" -var "KEYCLOAK_USER_PASSWORD=$KEYCLOAK_USER_PASSWORD"
          exit $APPLY_EXIT_CODE # Preserve the original exit code
        fi
        set -e # Re-enable exit on error